# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  name: 'mypool2'  # Use your defined agent pool
  demands: agent.name -equals desktopAgent2
variables:
  buildConfiguration: 'Debug'  # Set build configuration
  solution: 'C:\Users\Phillip Dao\Downloads\seleniumStudy17122024-17122024\trainingRepository1\lesson4SeleniumStudy17122024-17122024.sln'  # Solution file location
 
steps:
# Use the latest .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Adjust for your .NET SDK version
    installationPath: $(Agent.ToolsDirectory)/dotnet
 
# Restore dependencies
- script: dotnet restore $(solution)
  displayName: 'Restore Dependencies'
 
# Build the solution
- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'
 
# Run Unit Tests
- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --logger trx
  displayName: 'Run Unit Tests'
